### ISSUE TITLE
Publishing Audio

### ISSUE THREAD

**Issue by ksigWyatt** [WycliffeAssociates/8woc2017#120]
## User Story 
As a translator, I want to publish audio recordings so that the world can hear the gospels.

### Acceptance Criteria
- [x] Files are MP3 and are in a ZIP archive
- [x] Files are located in a separate *Publish* folder in *Media*
- [x] ZIP Files are named with the language, version, and chapter
- [x] MP3 files are merged into one file

## Tasks
- [x] Creae new endpoint for publishing selected audio files.
- [x] Files are converted into one MP3 file.
