### ISSUE TITLE
UI to upload source audio

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#14]
## User Story
As a translator, I want to choose source audio for a project from a .tr file so I can use it for checking instead of the source audio associated with each take

## Acceptance Criteria
- [ ] You can upload a .tr file and set it as your source audio

## Tasks
- [ ] UI for uploading .tr file and selecting it as your source audio
- [ ] accommodate imported source audio and put source verses/chunks in the correct place
