### ISSUE TITLE
Sync tab/storage

### ISSUE THREAD

**Issue by lcheng49** [WycliffeAssociates/8woc2017#17]
### User Story
As a translator user, I want to send files back to TR so that I can make more recordings.

### Acceptance Criteria
- [x] Source Audio sent back to tR

## Tasks
- [x] Unzip file into unique folder
- [x] Save meta data of each take to Database
- [x] Define what what files should be sent to tR
- [x] Create zip file containing new takes and comments to send to tR
