### ISSUE TITLE
Ability to delete takes

### ISSUE THREAD

**Issue by erica-zhong** [WycliffeAssociates/8woc2017#18]
## User Story
As a translator, I want to be able to delete takes so I can get rid of bad recordings clogging up the project quickly. 

- [x] Alongside each take is a way to delete it.

## Tasks
- [x] UI for deleting a take
- [x] Request backend to delete take from the database
