### ISSUE TITLE
Files are uploaded to the working area

### ISSUE THREAD

**Issue by ksigWyatt** [WycliffeAssociates/8woc2017#20]
### User Story
As a translator, I want my files to be uploaded so I can share my work

### Acceptance Criteria
- [x] Return notification of successful upload
- [x] Only allow ZIP files to be uploaded
- [x] Ensure that ZIP files only contain .wav files
- [x] Verify the file is in the working area
- [x] Return 403 response when files other than ZIP are uploaded

### Tasks
- [x] Creating error response when ZIP files containing files other than .wav files are uploaded

### Tests
- [x] automated test to check that error is returned when ZIP files containing files other than .wav is 
      uploaded
- [x] automated test to check for 403 response when files other than ZIP are uploaded

**Comment by Redmayspecial** [comment]
@Pinto18 should this card be assigned to ksigWyatt
