### ISSUE TITLE
Changes in Front End Updated in DB

### ISSUE THREAD

**Issue by Pinto18** [WycliffeAssociates/8woc2017#21]
## User Story

As a translator, I want my changes on the front end to be saved so that other users can see my changes

### Acceptance Criteria
- [x] File changes & deletions appear in the database
- [x] Changes appear across the platform & are permanent

## Tasks
- [x] Create API method to modify contents of DB or File System
- [x] Ensure that changes are permeated through the File System for any modified files 

## Testing
- [x] File changes appear in database

**Comment by dilipMaharjan** [comment]
@mXaln I suppose this has been accomplished and just need to verify
