### ISSUE TITLE
Can listen to source audio alongside translation

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#25]
## User Story
As a translator, whenever I listen to translated audio, I want source audio of the same text available alongside to listen to so I can check the translation

## Acceptance Criteria
- [ ] When I look at takes, there's a way to play source audio for each one
- [ ] When I select multiple segments to play, there's a way to play corresponding source audio of those segments

## Tasks
- [x] UI that displays source audio next to each chunk/verse
- - [x] Button for playing source audio
- - [x] Put the button next to each chunk
- [x] UI that displays source audio for selected segments next to whatever combination of segments user selects
- [ ] combine source audio for selected chunks/verses whenever user wants to listen to translation of selected chunks/verses
