### ISSUE TITLE
Display and listen to comments for a take

### ISSUE THREAD

**Issue by erica-zhong** [WycliffeAssociates/8woc2017#26]
## User Story
As a translator, I want to record comments and listen to my recorded comments for particular takes so that those takes can be improved.

## Acceptance Criteria
- [x] I can view and play audio comments associated with a particular take.
- [x] Recording comments is on the same screen as listening to comments.

## Tasks
- [x] UI to display and listen to the audio comments associated with the take
- [x] UI to record an audio comment and have the comment show up underneath in the same modal
