### ISSUE TITLE
Create Source Audio File

### ISSUE THREAD

**Issue by lcheng49** [WycliffeAssociates/8woc2017#27]
### User Story
As a translator, I want to export source audio files so I can translate into target language.
 
### Acceptance Criteria

- [x] Create TR files including proper source audio 
- [x] Source audio in TR file formatted in MP3

## Tasks
- [x] Convert files to one large MP3 file before creating Source Audio
## Tests (TDD)
- [ ]  Check for file extension .tR in response(ann)
- [ ]  Check that .tR directory exists (ann)
- [ ] Check that file is MP3 extension (ann)

**Comment by ksigWyatt** [comment]
Merged into #32 - there was a little too much overlap between the 2 Stories
