### ISSUE TITLE
Store metadata in database with file reference

### ISSUE THREAD

**Issue by annjones2** [WycliffeAssociates/8woc2017#29]
## User Story
As a translator, I want to access the detailed information associated with each file so that I can view that information later.

### Acceptance Criteria
- [x] Retrieve metadata from API call
- [x] Returns the correct data for what is requested
- [x] Data is returned in JSON format for the files requested

## Tasks
- [x] POST method works 

### Test Cases
Query the database for files that are associated with specified metadata.  Check for the following expected outcomes:
- [x] Empty return 
- [x] Non-empty return
