### ISSUE TITLE
Publish work

### ISSUE THREAD

**Issue by lcheng49** [WycliffeAssociates/8woc2017#32]
## User Story
As a translator I want to export my work so other translators/myself can access/listen

### Acceptance Criteria

- [x] Files are available in MP3 
- [x] Files are available to the tR app through .tr source audio
- [x] Create TR files including proper source audio
- [x] Source audio in TR file formatted in MP3

## Tasks
- [x] Files are converted to MP3 then zipped into an archive
- [x] Copy files to *export* folder to process them for extraction
- [x] Copied files are removed to save disk space after archival
- [x] Add files to .tR type
- [x] Use ArchiveOfHolder so we can actually create .tR files
- [x] Run ArchiveOfHolder locally on the Django Server so that the .tR packaging works properly
- [x] Remove hardcoded folders so the API can access anyone of the folders 

### Tests

- [x] Automated test where API receives request for project and test verifies that appropriate files are sent out. (System test with front end)

- [x] ~~Automated test where we verify that requested files are in their appropriate directory.~~
       _Test case already handled in Create Zip Files From Wav Files Test Cases_

**Comment by ksigWyatt** [comment]
Imported Acceptance Criteria from #27

**Comment by ksigWyatt** [comment]
Publish vs Export?
