### ISSUE TITLE
Pick final take that will be published for each segment

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#40]
## User Story
As a translator, I want to be able to pick which take is the final one that should be published for each segment

## Acceptance Criteria
- [x] For each chunk, there's a way to mark one take as the desired take

## Tasks
- [x] UI for marking a take as a desired one  
- [x] Mockups for these UIs: @itsmichaellima
