### ISSUE TITLE
Author information view 

### ISSUE THREAD

**Issue by itsmichaellima** [WycliffeAssociates/8woc2017#44]
As a translator, I want to view for each take: 

- author

- rating

- timestamp

so I know how and what to work on.

## Acceptance criteria 

- [ ] author

- [ ] timestamp

- [ ] rating 

**Time Estimation : 5**

## Tasks
- [x] Basic component for displaying take info
- [ ] Style component to look like mockups
- [ ] Integrate rating stars
- [ ] Come up with fake/template data
