### ISSUE TITLE
User interface for marking chapter as ready to publish + ability to listen to it

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#45]
## User Story
As a translator, I want a way to mark a chapter as ready to publish with my selected takes and listen to it to prepare for publishing

## Acceptance Criteria
- [x] Once takes have been chosen for each segment that's present in the project, you can choose to mark a chapter as done/ready to publish
- [x] When a chapter is done, there's a way to play its selected takes stitched together
- [ ] When a chapter is marked as done, there is indication of it on the takes page and the chapter listing page

## Tasks
- [x] Button for marking a chapter as done/ready to publish appears once takes have been chosen for each segment
- [x] For all chapters marked as done, UI for playing selected takes stitched together
- [ ] If a chapter is marked as done, there is some indication of it on the takes page and the chapter listing page
