### ISSUE TITLE
Download a project

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#47]
## User Story
As a translator, I want a way to export a book with all the takes so I can share the work/pass it on to Translation Recorder

## Acceptance Criteria
- [x] There is a UI for each project to download the project
- [x] You can download a file .zip file with all the takes in the project 

## Tasks
- [x] Button for downloading
- [x] ~~UI for choosing how to download~~
_Always going to be a zip_
- [x] Request back-end to get file, pass the file on to user to download

### Blocked
- [x] Ensure that the returned file is not corrupt after download

**Comment by ksigWyatt** [comment]
### Blocked by

/api/zip_files/ returns
404 Not Found
nginx/1.10.3 (Ubuntu)

**Comment by ksigWyatt** [comment]
### Blocked By
/api/zip_files/
Returns a file on our UI that is corrupt.

**Comment by ksigWyatt** [comment]
## Confirmed an issue with the back-end data

Here is the raw response from the server in it's RAW Unicode format
_I have truncated data so that it's not too long_


### Corrupted return
```
config: Object
data : "PK ~�Jq��!!>en-x-demo2/ulb/mrk/6/en-x-demo2_ulb_b42_mrk_c06_v10-11_t07.mp3ID3#TSSELavf57.56.100��@�Info��
"$&),.0468;>@CFHJMPRUWZ\_adgiknqsuy{}��������������������������������������������������Lavc57.64$���v���P�	��6�a���0�@�&M=h������������B�����������s$D!����  �|ϔp|����|D�cB#$jg�0�x�b��L�7݇��X��xu�S%o���"�^������z�����@�T@~��k>m4f�����e�>e#������������]�^ VҼ_���R��ܯA��u��t�):N!�^��C=��!�ꓭ0s.���L��
��C�.����	X뺢5Q������g���3����V]Ba1$LM�]��Z��m��3�↵��%7��4���/����(�`�	V��Yo��a�L3��{ڦ���x��^���{������1�c&,�a~й@K��fR]�Rn�Ro~Y� N2���R����=��oAY��v� ��|"�4M��[Q΄3�+��↵6�Z5��ę"%�T
r�Ԣ�2VG
�6��5#���`���&����H�r�:�;G�E����"	)�*!↵�@f`��D��p�↵�{�N	@\�B�0'�I�_S�hj�ϩ�i�\��R"���T���su&�↵L�����}��R�↵w�2�/��j ���R�	��9���	s(0�1���Q����!@ �vhB�m��C��`���l��h�|����qse'��2ج��������Y�M�Y]���>7�����Q�H��H��+��e�Ͽ5�K�j4*B(��64	>Mr@/�2��F℆0i)8�w�����yQ��L��ms�6������������G��=J�(Z�\↵↵��R����;\�x����
0�����"С.I8W�1Ș�\�e͈�e��k6{J�_�{?�C��tq�VeL���u�B�2'8�jP�b�-:�Unr���J'!oy!Bq�*�I
)c���d�A�&�rt!&yS�iv7�]�&n�@H��%�;ji�k��*W#� �-��V���E7 ��#}���v����n &�d��v��L���R����=�0�A~������k�
��#�d��Iys-����$�� u�R��vV�T���g��8}Կʿm�����{�E�T���M�f�,�����v��{���$�1ͩj�n'Js�S��6�E:-���#h��P�c(��8����[� pBE�0������fJ���X�c�0�ϗJ�bB��Lbqҿ޿����@��HB�@�S*��R��"
headers: Object
request: XMLHttpRequest
status: 200
statusText :"OK"
__proto__ : Object
```


### Good Return

```
data: "PK     ûJqçÆ! ! >   en-x-demo2/ulb/mrk/6/en-x-demo2_ulb_b42_mrk_c06_v10-11_t07.mp3ID3     #TSSE     Lavf57.56.100           ÿû@À                 Info     Œ ô 
"$&),.0468;>@CFHJMPRUWZ\_adgiknqsuy{}€ƒ…ˆ‹’•—šœŸ¡¤¦©¬®°³¶¸º¾ÀÂÅÈÊÍÐÒÔ×ÚÜßáäæéëîñóõøûý    Lavc57.64            $ð     ôŒáv™     ÿûPÄ  	€Ÿ6Ôa€¨0À  @ ü&M=hˆ»»»»±ŸñÝÝÝÜ  B¢»»¢ÿÏ÷s$D!üÁð  €|Ï”p|ÿÿÿ | D¼cB#$jg»0ÃxÐb²êLÝ7Ý‡“X–xuÈS%o—‚²"€^êÔ­ºz­ÒèÓ@ÕT@~ËÕk>m4fö™ø¦e¯>e#ÿÿÿÿþ¢ÿÝÿü] ‘^   VÒ¼_ÿûRÄ€Ü¯A¼ó u™étô):N!èŽ^’ŽC=ˆ¸!¬ê“­0s.À³äLµ‰
‰áCè.šÐôä	Xëº¢5Q¾±üùËûg¾õÃ3˜òãûV]Ba1$LM]«§Zúñmúõ3×
²É %7ÀÖ4‡™Š/àƒ”Ó(Û`	VœôYo“˜a¶L3‚•{Ú¦†¹¥x“‘^¼¦¦{’¼»þÉ1ôc&,a~Ð¹@KÀ±fR]äRnäRo~Yœ    N2¯ÿûRÄ ‹ ¯=§˜oAY•¥vŸ  ¤|"ž4MåÓ[QÎ„3²+”é
6ÐZ5ÒôÄ™"%€T
rèÔ¢€2VG
Ò6¥±5#òÚÆ`¨ÞÆ&€ Šå¥HÔr²:í‹;G¯Eÿ¥Ž²" 	) * !
²@f`¶DíÒpº
Ö{¼N	@\†BÌ0'‡Iô_S hjšÏ©i™\À´R"„áÓTé¨Àòsu&£
L²âÁ¼é}ùR±
 w¤2 /  œìj ¬ÿûRÄ	 ˆÁ9˜÷€	s(0 1‘‰£Q”‡¶¾!@ ävhBàm³‹C›ž`¼†¤l»·hÕ|ýÅøýqse'Þâ2Ø¬òªÜÙÕë‰áÒþYñMâ‘Y]ëø¶>7ÜàÃðÑQýHôåHø¸+´²e¤Ï¿5ÈKÅj4*B(› 64	>Mr@/‘2šð–¾Fâ„†0i)8áwÁŠ¬«¥yQ¶ñLÉôms×6‰‡þ¬×ÿÿÿú—Gÿè =J¶(ZÀ\"
headers: Object
request: XMLHttpRequest
status: 200
statusText :"OK"
__proto__ : Object
```

**Comment by ksigWyatt** [comment]
**Fixed issues**
