### ISSUE TITLE
View takes by chapter and chunk/verse

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#48]
## User Story
As a translator, I want to view takes by chapter and chunk/verse so I can find ones to work on

## Acceptance Criteria
- [ ] Display all takes for a selected chunk/verse of a selected chapter

## Tasks
- [ ] Figure out whether to display based on chunk or based on verse
- [x] UI for displaying info
- - [x] Basic components
- - [x] Integrate ratings, audio player, source audio
- - [ ] Style with drop down boxes, etc

**Comment by sheesania** [comment]
Question for Laurie/Joe: How should we deal with .wav's that may be of verses, chunks, different size chunks, etc? Will we have verse markers to use? (If we don't have verse markers, or they're incorrect, is it acceptable to just display the whole .wav under the first verse we can associate it with?) See mockup on board of display for different size segments
