### ISSUE TITLE
Set ratings

### ISSUE THREAD

**Issue by erica-zhong** [WycliffeAssociates/8woc2017#49]
## User Story
As a translator I want to set ratings for takes so that I can communicate which takes are preferred to others.

## Acceptance Criteria 
- [x] Alongside each take is a way to set the rating for it.

## Tasks
- [x] UI for setting rating
- [x] Send backend a request to update rating in the database

**Comment by Redmayspecial** [comment]
@erica-zhong   "As a translator I want to set ratings for takes to continue work on them."  maybe change to ....for takes so that I can communicate which takes are the best/preferred to others
