### ISSUE TITLE
See Ratings

### ISSUE THREAD

**Issue by erica-zhong** [WycliffeAssociates/8woc2017#50]
## User Story
As a translator, I want to see ratings for each take so that I can assess the quality of each take.

## Acceptance Criteria 

- [ ] Display rating alongside each take

## Tasks

- [ ] Request rating info from backend
- [x] Display rating info in UI
- - [x] Basic star component
- - [ ] Integrate into takes, etc

**Comment by Redmayspecial** [comment]
@erica-zhong   Can you finish the user story with a "so that..."?
