### ISSUE TITLE
Listen to takes

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#53]
## User Story
As a translator, I want to listen to takes to assess them

## Acceptance Criteria
- [ ] Ability to listen to takes in the browser

## Tasks
- [ ] Play audio in the browser
- [ ] UI for playing audio (play/pause button, waveform, etc) in display of takes
