### ISSUE TITLE
User Interface for stitching together takes and listening to them

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#57]
## User Story
As a translator, I want to be able to select takes and listen to them together to assess their quality

## Acceptance Criteria
- [x] There is a user interface to select takes for multiple segments and playing them together

## Tasks
- [x] UI for selecting several takes and choosing to play them
- [x] a play button for playing stitched together takes
