### ISSUE TITLE
Display and search/sort available books and languages

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#58]
## User Story

As a translator I want to view all the available languages and books in each language
so I can find the one I want to contribute to.

 ## Acceptance Criteria

- [ ] Display the language of available translation projects

- [ ] Display the books available in the selected language

- [ ] Ability to search through and sort projects

## Tasks
- [ ] UI to display languages and books
- [ ] UI for searching and sorting
