### ISSUE TITLE
Accessible, intuitive UI

### ISSUE THREAD

**Issue by erica-zhong** [WycliffeAssociates/8woc2017#60]
## User Story
As an illiterate user I want to easily identify features and navigate through the website 

## Acceptance Criteria
- [x] user is able to navigate through the website with minimal text 

## Tasks
- [x] minimal text (book names, etc.)
- [x] utilizes colors and symbols in an intuitive way 
- [x] logical way to navigate through website
