### ISSUE TITLE
View project information (data)

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#63]
## User Story

As a translator I want to view information like checking level and translation type for each project _in the database_ so I can find the right one and know how to work on it. 

 ## Acceptance Criteria

- [ ] For each book see:
         - Translation type                              
         - Checking level per chapter       
         - How much is finished for each book                               
         - Contributors for each chapter and book
         - Time stamps for modifications for each chunk and book

## Tasks
- [ ] Request project info from the backend database: @erica-zhong 
- [ ] Pass it to the UI display components: @erica-zhong
