### ISSUE TITLE
Access available books and languages (data)

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#64]
## User Story

As a translator I want to view all the available languages and books in each language _from the database_ so I can find the one I want to contribute to.

 ## Acceptance Criteria

- [ ] Display the language of available translation projects

- [ ] Display the books available in the selected language

- [ ] Ability to search through and sort projects

## Tasks
- [x] Request languages from backend: @dvmarchuk 
- [ ] Request projects from backend (possibly sorting through takes to determine what projects there are): @sheesania
