### ISSUE TITLE
Listen to takes (data)

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#65]
## User Story
As a translator, I want to listen to takes from the database to assess them

## Acceptance Criteria
- [x] Ability to listen to takes from the database in the browser

## Tasks
- [x] Request audio location from backend: @nathanalbers 
- [x] Pass audio stream to player component: @nathanalbers
