### ISSUE TITLE
View takes by chapter and chunk/verse (data)

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#68]
## User Story
As a translator, I want to view takes from the database by chapter and chunk/verse so I can find ones to work on

## Acceptance Criteria
- [x] Display all takes for a selected chunk/verse of a selected chapter in the database

## Tasks
- [x] Get information from backend about available files for this project
- [x] Figure out what chapters there are and pass them to UI chapter display component
- [x] Find chunks for the selected chapter and takes for each one
- [x] Pass data to the UI chunk/take display component
