### ISSUE TITLE
Make all data available for API

### ISSUE THREAD

**Issue by annjones2** [WycliffeAssociates/8woc2017#7]
### User Story
As a translator, I want my files to be visible on an application so that I can interact with them intuitively.

### Acceptance Criteria

- [x] Access and view files

## Tasks
- [x] Create custom queries in the DB
*Relates to #91*
- [x] Expose database to front end through API.

## Tests (test when front end is available)
- [ ]  System testing: Can front end interact with file system?

**Comment by annjones2** [comment]
## Acceptance Criteria
-[] user must be able to access files

**Comment by annjones2** [comment]
Expose database to front end through API.

**Comment by ksigWyatt** [comment]
This has been achieved - and is shown from other stories
