### ISSUE TITLE
Pick final take to export for each segment (data)

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#72]
## User Story
As a translator, I want to be able to pick which take should be exported for each segment and have that information stored

## Acceptance Criteria
- [ ] For each chunk, there's a way to mark a take as the desired one, or mark that no takes should be exported for this chunk, and this information is stored in the database

## Tasks
- [ ] Request backend to update database with info about which take is the desired one

- [ ] Talk with database team about information they need to store/have available through the API: @sheesania
- [ ] Write request to API for setting a take as the desired one
- [ ] Write request to API for setting a take as not the desired one anymore
