### ISSUE TITLE
Ability to delete comments (data)

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#74]
## User Story
As a translator, I want to be able to delete comments on takes

## Acceptance Criteria
- [x] Ability to delete a comment on a particular take and have it removed in the backend

## Tasks
- [x] When comment is deleted in the UI, it no longer exists anywhere and is disconnected from particular take (request backend to remove it/mark is as deleted/whatever in the database)

**Comment by erica-zhong** [comment]
Bugs 
- [ ] can't delete just added comments, wait until back end returns comment id after post request
- [ ] hide comment player after save button clicked
- [ ] either close button or close icon works
- [ ] alert for deleting comments to confirm
