### ISSUE TITLE
Can listen to source audio alongside translation (data)

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#76]
## User Story
As a translator, whenever I listen to translated audio, I want source audio that was used to create those specific takes to be available alongside to listen to so I can check the translation

## Acceptance Criteria
- [x] When I look at takes or select multiple segments to play, I can play the right source audio from the database that was used to create those takes/segments

## Tasks
- [ ] Request source audio from the backend

- [ ] UI mockup of how we'll listen to source audio for each take: @itsmichaellima 
- [ ] Send request to backend for source audio stream for particular take: @nathanalbers 
- [x] Pass returned audio stream from backend to source audio player component: @nathanalbers
