### ISSUE TITLE
Create ZIP Files from wavs

### ISSUE THREAD

**Issue by ksigWyatt** [WycliffeAssociates/8woc2017#80]
## User Story

As a translator, I want to be able to import new recordings for me to use on translationRecorder, so that I can continue to work.

### Acceptance Criteria
- [x] Create ZIP file from directory of .wav files
- [x] Files are converted to MP3 first, in order to save disk space 
- [x] Ensure .wav files still exist in File System file after compressed to zip archive

## Tasks
- [x] Create zip file that contains .wav files
- [x] ~~Convert ArchiveOfHolder to Python so we can actually create .tR files~~
*added to US: #32*
- [x] Convert files to MP3 before archiving

### Tests
- [ ] automated test to see if temporary directory of .wav files are turned into a zip file
- [ ] ~~check that .wav files still exist in file system~~
         _Risk associated with this test is very low attributed to unlikely outcome._ - Nick
- [ ] automated test where an equivalent MP3 file is created from each .wav file

**Comment by ksigWyatt** [comment]
Added task to #32
