### ISSUE TITLE
Can listen to source audio for multiple selected takes

### ISSUE THREAD

**Issue by sheesania** [WycliffeAssociates/8woc2017#83]
## User Story
As a translator, whenever I listen to translated audio stitched together, I want source audio of the same text available alongside to listen to so I can check the translation

## Acceptance Criteria
- [x] When I select multiple segments to play, there's a way to play corresponding source audio of those segments

## Tasks
- [x] UI for playing source audio when you select multiple chunks/verses
- [x] combine source audio for selected chunks/verses whenever user wants to listen to translation of selected chunks/verses
