### ISSUE TITLE
Filter changes during uploads

### ISSUE THREAD

**Issue by ksigWyatt** [WycliffeAssociates/8woc2017#88]
## User Story 
As a translator, I want the files uploaded that have been changed so I don't have to upload duplicates.

### Acceptance Criteria

- [x] API removes non-changed files during upload

## Tasks
- [x] Create a new server response for zip files containing duplicate .wav files
*The response needs to return some 'helpful' information to the application making the call*
- [x] Design API to return a list of changes that have been made that need to be uploaded. 

## Tests
- [x] Test that files with changes are the only ones uploaded
- [x] Test that duplicate .wav files return same hash code
