### ISSUE TITLE
Send all project info to Front End

### ISSUE THREAD

**Issue by ksigWyatt** [WycliffeAssociates/8woc2017#91]
## User Story
As a front-end developer I want the project info for any version of any book in any language from the database, so that I can display the information to the user.

### Acceptance Criteria
- [x] Returns each projects: 
  - [x] Book
  - [x] Language
  - [x] Version
  - [x] Contributors
  - [x] Date modified (latest date modified of the takes that are part of the project)
  - [x] Percentage complete
- [x]  Returns as a list of type JSON for all the files being requested

- [x] Returns each chapter for specified project:
  - [x] Chapter num
  - [x] Checked_lvl
  - [x] Contributor
  - [x] Timestamp
  - [x] Percent Complete
- [x]  Returns as a list of type JSON for all the files being requested
## Tasks
- [x]  Return all the proper information 
*including:*
  -  Authors of takes that are part of the project
  - Latest date modified of the takes that are part of the project
- [x] Add fake data to the DB that contains the source audio for each project
    - [x] Modify metadata from tR to make data contain correct fields
- [x] Assign source audio to files & projects as they are uploaded

### Stretch Goal
- [ ] Filter by contributors, percentage completed, etc.

## Testing
- [x]  testing redundant with #29

**Comment by ksigWyatt** [comment]
More detailed comments are detailed inside [this text file](https://github.com/WycliffeAssociates/8woc2017/files/1132002/91.txt)

**Comment by lcheng49** [comment]
The contributor section for both endpoints should be modified later when we put in users.
