### ISSUE TITLE
Upload Source Audio to DB

### ISSUE THREAD

**Issue by ksigWyatt** [WycliffeAssociates/8woc2017#95]
## User Story
As a translator, I want to upload the source audio that I used to translate from so that others can compare my translation against the source.

### Acceptance Criteria
- [x] Upload tR source files are added to the database
- [x] Uploads for source audio only allow .tR file types

## Tasks
- [x] Un-package TR files using AOH running on server
- [x] Flag audio files in the DB as a source
- [x] Send audio files to front-end using query based on source flag for given projects
